routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


use Maatwebsite\Excel\Facades\Excel;
use App\Exports\Dividen\DividenExport;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\Admin\Dividen\DividenController;

Route::view('503', 'errors.test');

$investor = function () {

    Route::get('/daftar-dan-langgan', 'Investor\InvestorController@signup')->name('langganan-syer');

    Route::get('/Daftar', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/daftar', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/langganan-syer', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/affiliate', 'Investor\InvestorController@signup');
    Route::post('/langganan-syer', 'Investor\InvestorController@create_order')->name('langganan-syer-exe');
    Route::get('/langganan-syer/pengesahan', 'Investor\InvestorController@verify')->name('langganan-syer-pengesahan');
    // semak keanggotaaan
    Route::get('/keanggotaan/cari', 'Investor\SemakKeanggotaanController@findUser')->name('member.getuser');
    Route::get('/keanggotaan/semak', 'Investor\SemakKeanggotaanController@index')->name('member.verify');


    //Pembayaran manual
    Route::get('/langganan-syer/pembayaran-manual', 'Investor\InvestorController@buy_manual')->name('langganan-syer-manual');
    Route::post('/langganan-syer/pembayaran-manual', 'Investor\InvestorController@buy_manual_exe');

    Route::get('/langganan-syer/terima-kasih', 'SenangPayController@thankyou');


    Route::get('/hantar-bukti-pembayaran', 'Investor\InvestorController@paymentproof')->name('hantar-bukti-pembayaran');
    Route::post('/hantar-bukti-pembayaran', 'Investor\InvestorController@paymentproofexe')->middleware('optimizeImages');
    //

    Route::get('/login', 'Investor\InvestorController@index')->name('login');
    Route::get('/logmasuk', 'Investor\InvestorController@index')->name('login');
    Route::get('/LogMasuk', 'Investor\InvestorController@index')->name('login');
    Route::get('/', 'Investor\InvestorController@index')->name('login-root');
    Route::get('/logout', 'Investor\InvestorController@logout')->name('logout');
    // LOGIN FOR ANGGOTA
    Route::post('/auth/login/anggota', 'Investor\InvestorController@login_by_email_exe')->name('login-exe');
    Route::get('/forgot-password', 'Investor\InvestorController@forgot_password')->name('login');

    Route::get('/ikoop-migration', 'Investor\InvestorController@ikoopfirsttime')->name('ikoopfirsttime');
    Route::post('/ikoop-migration', 'Investor\InvestorController@ikoopfirsttimeexe');

    Route::get('/ikoop-migration/verification', 'Investor\InvestorController@ikoopfirsttime_2');

    Route::get('/ikoop-migration/verification/otp', 'Investor\InvestorController@ikoopfirsttime_3')->name('ikoopfirsttime3');

    Route::get('/ikoop-migration/verification/otp/send', 'Investor\InvestorController@sendOtp')->name('ikoopfirsttime3');

    Route::post('/ikoop-migration/verification/otp/submit', 'Investor\InvestorController@submitOTP')->name('ikoopfirsttime4');

    Route::get('/ikoop-migration/verification/thank-you', 'Investor\InvestorController@ikoopfirsttimethankyou')->name('ikoopfirsttimethankyou');

    Route::get('/email-activation/{token}', 'Investor\InvestorController@email_activation');

    Route::get('/dashboard', 'Investor\InvestorLoggedController@home')->name('dashboard');
    Route::get('/home', 'Investor\InvestorLoggedController@home')->name('dashboard');

    Route::get('/profile', 'Investor\InvestorLoggedController@edit_org_2');
    Route::get('/profile2', 'Investor\InvestorLoggedController@edit_org_2');

    Route::get('/syer', 'Investor\InvestorLoggedController@invest');
    Route::get('/syer/{id}', 'Investor\InvestorLoggedController@invest_detail');

    Route::get('/statement', 'Investor\InvestorLoggedController@statement');

    //DOWNLOAD PDF FOR INVESTOR
    Route::get('download_public', 'Investor\PdfController@download_public');

    Route::get('/linkstorage', function () {
        Artisan::call('storage:link');
    });

	if (env('ENABLE_DIVIDEN_MODULE', true)) {

	Route::get('/dividen', 'Investor\DividenController@index');

	Route::get('/dividen/download', 'Investor\DividenController@dividen_statement_download');


	Route::get('/dividen/withdraw', 'Investor\DividenController@withdraw');
	Route::post('/dividen/withdraw', 'Investor\DividenController@withdraw_exe');
	}


    Route::get('/change-password', 'Investor\InvestorLoggedController@changepassword');
    Route::post('/change-password', 'Investor\InvestorLoggedController@changePasswordExe');

    Route::get('/investor/edit/resend-email', 'Investor\InvestorLoggedController@activation_email');


    if (env('ENABLE_AFFILIATES', false)) {
        Route::get('/affiliates', 'Investor\AffiliatesController@invest');
        Route::post('/affiliates/withdraw', 'Investor\AffiliatesController@withdrawal');
        Route::get('/affiliates/penyata-komisen', 'Investor\AffiliatesController@getStatement');
        Route::get('/affiliates/penyata-komisen/cetak/{id}', 'Investor\AffiliatesController@printStatement');
        //        Route::get('/affiliates/withdraw', 'Investor\AffiliatesController@affliate_withdraw')->name('index');
        //        Route::post('/affiliates/withdraw', 'Investor\AffiliatesController@affliate_withdraw_exe')->name('index');
        Route::post('/affiliates/apply', 'Investor\AffiliatesController@apply_affiliate');
    }

    Route::view('terma-syarat', 'terma-syarat');
    Route::view('success-proof-payment-upload', 'investor.after-upload-proof-payment');

    Route::get('/dapatkan-kata-laluan', 'Auth\ResetPasswordController@showResetForm');
    Route::post('/kata-laluan/sahkan-kad-pengenalan', 'Auth\ResetPasswordController@verifyIc');
    Route::get('/kata-laluan/sahkan-no-telefon', 'Auth\ResetPasswordController@verifyMobileNumber');
    Route::any('/kata-laluan/hantar-kata-laluan-sementara', 'Auth\ResetPasswordController@sendTemporaryPassword');

    Route::get('/set-kata-laluan-baru', 'Investor\InvestorLoggedController@resetPassword');
    Route::post('/set-kata-laluan-baru', 'Investor\InvestorLoggedController@resetPasswordExe');

    // Permohonan Berhenti
    Route::get('/permohonan-berhenti', 'Investor\InvestorLoggedController@terminate_membership');
    Route::post('/permohonan-berhenti', 'Investor\InvestorLoggedController@terminate_membership_submit');
    Route::get('/permohonan-aktif', 'Investor\InvestorLoggedController@reactivate_membership');
    Route::post('/permohonan-aktif', 'Investor\InvestorLoggedController@reactivate_membership_submit');
    // Buy Share
    Route::prefix('langgan-syer')->name('share.')->namespace('Investor')->group(function () {
        Route::get('', 'BuyShareController@buy')->name('buy');
        Route::post('', 'BuyShareController@store_buy')->name('buy');
        Route::get('pengesahan', 'BuyShareController@verify')->name('verify');
    });

    //SenangPay: Do not use auth middleware
    Route::post('/payment-gateway/senang-pay/submit', 'SenangPayController@submit')->name('senang-pay-submit');
    Route::post('/payment-gateway/senang-pay/submit-recurring', 'SenangPayController@submitRecurring')->name('senang-pay-submit-recurring');
    Route::get('/pembelian-share/terima-kasih-s', 'SenangPayController@result'); //temp route
    Route::get('/payment-gateway/senang-pay/result', 'SenangPayController@result');
    Route::any('/payment-gateway/call-backend/senang-pay', 'SenangPayController@callback')->name('senang-pay-callback');

    //Profile
    Route::middleware(['auth'])->prefix('investor')->name('investor.')->namespace('Investor')->group(function () {
        Route::post('edit/info', 'ProfileController@editInfoPemohon');
        Route::post('edit/attachment', 'ProfileController@editInfoMykad');
        Route::post('edit/address', 'ProfileController@editAlamatPemohon');
        Route::post('edit/contact', 'ProfileController@editKontak');
        Route::post('edit/jawatan', 'ProfileController@editPekerjaan');
        Route::post('edit/bank', 'ProfileController@editBank');
        Route::post('edit/waris', 'ProfileController@editWaris');
        Route::post('profile/submit', 'ProfileController@submit')->name('profile.submit');
    });

    Route::group(['middleware' => 'auth', 'prefix' => 'transaksi', 'namespace' => 'Investor\Transactions'], function () {

        Route::group(['prefix' => 'log'], function () {
            Route::get('/', 'LogsController@index')->name('investor.transactions.logs.index');
        });
    });
};

$admin = function () {

    //temp solution for when admin close browser, then open back and go to admin route while still logged in, the system
    //will redirect to /home. Need to fix this later
    Route::get('/home', function () {
        return redirect('admin/dashboard');
    });

    //SenangPay, no auth
    Route::any('/payment-gateway/call-backend/senang-pay', 'SenangPayController@callback')->name('senang-pay-callback');

    //Members
    Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
        Route::get('members/dashboard', 'MemberController@viewDashboard')->name('member.dashboard');
        Route::get('members', 'MemberController@index')->name('member.list');
        Route::get('members/new', 'Members\NewApplicantsController@index')->name('member.new');
        Route::get('members/ikoop', 'Members\IkoopApplicantsController@index')->name('member.ikoop');
        Route::get('members/reviewed', 'Members\ReviewedApplicantsController@index')->name('member.reviewed');

resources/views/admin/add-user.blade.php
@extends('admin.layouts')
@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/jquery.datetimepicker.css">
<style>
    #myTable td {
        padding: 2px 1px !important;
    }

</style>
@endsection
@pagetitle(['title'=>'Daftarkan Anggota (Manual)','links'=>['Pendaftaran']])@endpagetitle

@section('content')

<div class="container">
    <form action="{{route('admin.member.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        {{-- Add User form --}}
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <div class="card">
                            <div class="card-body">
                                @include('admin.users.partials.add-user-form')
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end card -->
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <!-- transaksi langganan -->
                        @include('admin.users.partials.add-user.transaksi-langganan')
                    </div>
                </div>
            </div>
        </div>

        {{-- Save button --}}
        <div class="row">
            <div class="col ">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <div class="d-flex align-items-center justify-content-between">
                                <h5>Simpan semua perubahan?</h5>
                                <button type="submit" class="btn btn-lg btn-primary text-capitalize font-weight-bold">Ya, teruskan
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


@endsection

@section('js')
<script src="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/build/jquery.datetimepicker.full.min.js" integrity="sha256-JADorIjphY5ztERiDARizkSMD2NW4HpsDlAyageYtFc=" crossorigin="anonymous"></script>

<script type="text/javascript">
    var utilitiesinit = () => {
        $('.mask').inputmask();
        $('.mykad-mask').inputmask('999999999999');
        $('.mobile-mask').inputmask({
            mask: '6999999999999'
            , rightAlign: false
        });
        $('.phone-mask').inputmask('6999999999999');
        $('.poskod').inputmask('99999');

        jQuery('.paid_at,.registration_date').datetimepicker({
            datepicker: true
            , timepicker: true
            , format: 'Y-m-d H:i:s'
        });

        $('.select2').select2({
            theme: 'bootstrap4'
        });
    }
    // initialize script
    utilitiesinit();

</script>

<script>
    $('a[data-toggle="pill"]').on('shown.bs.tab', function(e) {
        localStorage.setItem('activeTab', $(e.target).attr('href'));
    });

</script>
<script>
    function generatePassword() {
        var length = 8
            , charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
            , retVal = "";
        for (var i = 0, n = charset.length; i < length; ++i) {
            retVal += charset.charAt(Math.floor(Math.random() * n));
        }
        $('#pass').val(retVal);

    }

</script>

@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts')

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css" integrity="sha512-SUJFImtiT87gVCOXl3aGC00zfDl6ggYAw5+oheJvRJ8KBXZrr/TMISSdVJ5bBarbQDRC2pR5Kto3xTR0kpZInA==" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
@endsection

@section('header')
<div class="container mt-3">
    <div class="row d-none d-print-block">
        <div class="col mt-5">
            <div class="d-flex">
                <h3 class="text-4xl">{{\Carbon\Carbon::now()->translatedFormat('d F Y H:m:s')}}</h3>
            </div>
        </div>
    </div>
    <div class="row d-print-none">
        <div class="col">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h3 class="text-5xl">Selamat Datang, {{Helper::getFirstNameOnly(auth()->user()->name)}}</h3>
                    <p class="text-gray-600">Berikut merupakan statistik dan laporan semasa KoPPIM.</p>
                </div>
                <div>
                    <ul class="navbar-nav flex-row ml-auto d-flex align-items-center list-unstyled topnav-menu float-right mb-0">
                        <li class="dropdown d-none d-lg-block">
                            <a class="dropdown-toggle mr-0 rounded-full p-2 text-gray-600 hover:text-gray-800 active:text-gray-800 focus:text-gray-800 align-items-center" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                </svg>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <!-- item-->
                                <a href="javascript:void;" class="dropdown-item notify-item" id="printImage">
                                    Cetak halaman ini
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div> <!-- container-fluid -->
@endsection
@section('content')
<div class="container mt-3 mb-5" id="overall">
    <div class="row">
        <div class="col">
            <h3 class="text-sm text-gray-600 font-medium uppercase letter tracking-wider">Statistik Pendaftaran dan Keanggotaan (Keseluruhan)</h3>
        </div>
    </div>

    {{-- App\Widgets\StatistikKeanggotaan --}}
    {{ Widget::run('StatistikKeanggotaan') }}

    @widget('GrafStatistik')

    <div class="row">
        <div class="col">
            <h3 class="text-sm text-gray-600 font-medium uppercase letter tracking-wider">Statistik Transaksi Bayaran</h3>
        </div>
        <div class="col">
            <div class="d-flex flex-row space-x-2 justify-content-end align-items-end mb-2">
                <button type="button" class="btn btn-info" id="keseluruhan">Keseluruhan</button>
                <select name="" id="cams_month" class="form-control w-1/3">
                    <option value="">Sila Pilih</option>
                    @for($i=1;$i<13;$i++) <option value="{{$i}}">{{Carbon\Carbon::createFromFormat('m',$i)->translatedFormat('F')}}</option>
                        @endfor
                </select>
                <select name="" id="cams_year" class="form-control w-1/3">
                    <option value="">Sila Pilih</option>
                    <?php for($i = 2020;$i <= date("Y");$i++){ ?>
                    <option value="{{ $i }}">{{ $i }}</option>
                    <?php } ?>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @include('widgets.transaksi_bayaran_cams')
        </div>
        <div class="col">
            @include('widgets.transaksi_bayaran_senang_pay')
        </div>
        <div class="col">
            @include('widgets.transaksi_bayaran_raudhah_pay')
        </div>
        <div class="col">
            @include('widgets.transaksi_bayaran_ikoop')
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3 class="text-sm text-gray-600 font-medium uppercase letter tracking-wider">Statistik Prestasi Program Affiliate</h3>
        </div>
    </div>
    {{ Widget::run('StatistikAffiliate') }}
    <div class="row">
        <div class="col">
            {{  Widget::run('PencapaianAffiliate') }}
        </div>
    </div>
</div>
@endsection
@push('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.11.0/underscore-min.js" integrity="sha512-wBiNJt1JXeA/ra9F8K2jyO4Bnxr0dRPsy7JaMqSlxqTjUGHe1Z+Fm5HMjCWqkIYvp/oCbdJEivZ5pLvAtK0csQ==" crossorigin="anonymous"></script>
<script>
    $('#printImage').on('click', function() {
        window.print();
    })


    function cams_queries() {
        // default this year
        if ($('#cams_year').val() == "") {
            $('#cams_year').val(new Date().getFullYear())
        }

        return {
            year: $('#cams_year').val()
            , month: $('#cams_month').val()
        }
    }

    function selectorValue(data) {
        $('#jumlahKeseluruhanCams').html(data.jumlahKeseluruhanCams);
        $('#jumlahSyerCams').html(data.jumlahSyerCams);
        $('#jumlahFiCams').html(data.jumlahFiCams);
        $('#jumlahKeseluruhanSenangpay').html(data.jumlahKeseluruhanSenangpay);
        $('#jumlahSyerSenangpay').html(data.jumlahSyerSenangpay);
        $('#jumlahFiSenangpay').html(data.jumlahFiSenangpay);
        $('#jumlahKeseluruhanRaudhahpay').html(data.jumlahKeseluruhanRaudhahpay);
        $('#jumlahSyerRaudhahpay').html(data.jumlahSyerRaudhahpay);
        $('#jumlahFiRaudhahpay').html(data.jumlahFiRaudhahpay);
        $('#jumlahKeseluruhanIkoop').html(data.jumlahKeseluruhanIkoop);
        $('#jumlahSyerIkoop').html(data.jumlahSyerIkoop);
        $('#jumlahFiIkoop').html(data.jumlahFiIkoop);
    }

    function fetchTransaksi(data) {
        $.ajax({
            type: 'GET'
            , url: "{{ route('api.transaction.statistic') }}"
            , data: data
            , success: function(data) {
                $('.tarikh_tahun').html("(Keseluruhan)");
                selectorValue(data);
            }
        });
    }

    fetchTransaksi(cams_queries());

    $('#keseluruhan').click(function() {
        fetchTransaksi('');
    });

    $("#cams_month,#cams_year").on("change", function() {

        $.ajax({
            type: 'GET'
            , url: "{{ route('api.transaction.statistic') }}"
            , data: cams_queries()
            , success: function(data) {
                $('.tarikh_tahun').html($('#cams_month').val() + '/' + $('#cams_year').val());
                selectorValue(data);
            }
        });

    });

</script>
@endpush

resources/views/admin/maintenance.blade.php
@extends('admin.layouts')
@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/jquery.datetimepicker.css">
@endsection
@pagetitle(['title'=>'Set Mod Penyelenggaraan','links' => ['Tetapan Admin']])@endpagetitle
@section('content')
<div class="container">
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header bg-white font-weight-bold">
                Status Mod Penyelenggaraan
            </div>
            <div class="card-body">
                @if(Storage::disk('framework')->exists('down'))
                    <h2><span class="badge badge-success">
                        Aktif
                    </span></h2>
                    <span><form action="/admin/maintenance/destroy" method="POST">
                        @csrf
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Hentikan Mod Penyelenggaraan</button>
                        </div>
                    </form>
                    </span>
                @else
                <h2><span class="badge badge-warning">
                    Tidak Aktif
                </span></h2>
                @endif
            </div>
        </div>
        <div class="card">
            <div class="card-header bg-white font-weight-bold">
                Sila masukkan tempoh waktu penyelenggaraan
            </div>
            <div class="card-body">
                <form enctype="multipart/form-data" method="post" action="/admin/maintenance/store">
                    @csrf
                    <div class="form-group">
                        <div class="row">
                            <div class="col">
                                <label for="" class="d-block">Tarikh Mula Penyelenggaraan</label>
                            <input type="text" class="form-control" name="from" placeholder="" id="from" value="{{old('from')}}">
                                @error('from')
                            <p class="text-danger">{{$message}}</p>
                                @enderror
                            </div>
                            <div class="col">
                                <label for="" class="d-block">Tarikh Akhir Penyelenggaraan</label>
                            <input type="text" class="form-control" name="to" placeholder="" id="to" value="{{old('to')}}">
                            @error('to')
                            <p class="text-danger">{{$message}}</p>
                                @enderror
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <p class="text-danger">Peringatan! Pelanggan KoPPIM tidak akan dapat mengakses laman web ini
                            ketika
                            dalam
                            Mod Penyelenggaraan. Sila pastikan anda sudah memaklumkan kepada para pelanggan sebelum
                            mulakan Mod Penyelenggaraan.</p>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary font-weight-bold">Mulakan Mod
                            Penyelenggaraan</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
</div>
@endsection

@section('js')
<script src="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.21/build/jquery.datetimepicker.full.min.js"
    integrity="sha256-JADorIjphY5ztERiDARizkSMD2NW4HpsDlAyageYtFc=" crossorigin="anonymous"></script>

<script>
    jQuery('#from, #to').datetimepicker({
        format:'d/m/Y H:i'
    });
</script>
@endsection

resources/views/admin/users.blade.php
@extends('admin.layouts')

@pagetitle(['title'=>'Senarai Semua','links'=>['Keanggotaan']])@endpagetitle

@section('content')
<div class="container">
    <div class="row" style="">
        <div class="col-lg-6">
            <div class="input-group mb-3">
                <input type="text" id="search" class="form-control" value="{!! $search ?? ''!!}" placeholder="CARIAN MENGGUNAKAN NAMA, NO. TELEFON ATAU NO. MYKAD">
                <div class="input-group-append">
                    <button class="btn btn-primary font-weight-bold submit" onclick="search_data()">CARI</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex justify-content-center align-items-center mb-3">
                    @if($members)
                    Paparan {{number_format($members->firstItem(),0,"",",")}} Hingga {{ number_format($members->lastItem(),0,"",",")}} Daripada {{number_format($members->total(),0,"",",")}} Dalam Senarai
                    @endif
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    {{ $members->appends(request()->query())->links() }}
                </div>
            </div>
        </div>
        {{-- only will display on belum dikemaskini page --}}

        <div class="col-lg-12 col-xl-12">
            <div class="card">
                <div class="card-body">
                    @include('admin.users.partials.categories-tab')
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="thead-primary">
                                <tr>
                                    @if(request()->get('status') == 1)
                                    <th class="text-center">@sortablelink('approved_date', new HtmlString('TARIKH<br>DILULUSKAN'))</th>
                                    @else
                                    <th class="text-center">@sortablelink('created_at', new HtmlString('TARIKH<br>DAFTAR'))</th>
                                    @endif
                                    <th>@sortablelink('name', strtoupper('nama'))</th>
                                    <th class="text-center">NO. Anggota KoPPIM</th>
                                    <th class="text-center">NO. MYKAD</th>
                                    <th class="text-center">STATUS KEANGGOTAAN</th>
                                    <th class="text-center">LOG MASUK</th>
                                    <th class="text-center">JUMLAH BAYARAN</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($members as $key=> $member)
                                <tr>
                                    {{-- only will display on belum dikemaskini page --}}
                                    <td class="text-center">{!! $member->created_at->translatedFormat("d/m/Y \<\b\\r\> h:i:sa") !!}</td>
                                    <td><a href="{{route('admin.member.view',$member->id)}}">{{ $member->name }}</a></td>
                                    <td class="text-center">{{ $member->no_koppim ?? 'TIADA NO. ANGGOTA KoPPIM' }}</td>
                                    <td class="text-center"><a href="{{route('admin.member.view',$member->id)}}">{{ $member->ic }}</a></td>
                                    <td class="text-center">{!! Helper::status_text($member->status) !!} <br>
                                        {!!
                                        $member->approved_date != '' ? $member->approved_date->format("d/m/Y \<\b\\r\> h:i:sa"):''
                                            !!}
                                    </td>
                                    <td class="text-center">
                                        @php
                                        $last_login = \Spatie\Activitylog\Models\Activity::where('log_name','user_auth')->where('subject_id',$member->id)->latest()->first();
                                        @endphp
                                        {!! ($last_login) ? $last_login->created_at->translatedFormat('d/m/Y \<\b\\r\> h:i:sa') : 'TIADA' !!}
                                    </td>
                                    <td class="text-center">
                                        @php
                                        $total = App\Mongo\Payment::where('ic',$member->ic)->where('returncode','100')->sum('amount');
                                        @endphp
                                        RM{{number_format($total,2,".",",")}}
                                    </td>
                                </tr>
                                @empty
                                @tablenoresult
                                @endtablenoresult
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div><!-- card-body -->
            </div><!-- card -->
        </div>
    </div>

</div><!-- container -->

@endsection

@section('js')

<script>
    function search_data() {
        var search = $('#search').val();
        @if(request()->has('status'))
            window.location.href = "{{route('admin.member.list')}}?status={{request()->get('status')}}&search=" + search;
        @else
            window.location.href = "{{route('admin.member.list')}}?search=" + search ;
        @endif
    }

    $(document).on("keypress", ".input-group:has(input:input, span.input-group-btn:has(.btn)) input:input", function(e) {
        if (e.which == 13) {
            $(this).closest(".input-group").find(".input-group-append > .submit").click();
        }
    });

</script>
@endsection