routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


use Maatwebsite\Excel\Facades\Excel;
use App\Exports\Dividen\DividenExport;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\Admin\Dividen\DividenController;

Route::view('503', 'errors.test');

$investor = function () {

    Route::get('/daftar-dan-langgan', 'Investor\InvestorController@signup')->name('langganan-syer');

    Route::get('/Daftar', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/daftar', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/langganan-syer', 'Investor\InvestorController@signup')->name('langganan-syer');
    Route::get('/affiliate', 'Investor\InvestorController@signup');
    Route::post('/langganan-syer', 'Investor\InvestorController@create_order')->name('langganan-syer-exe');
    Route::get('/langganan-syer/pengesahan', 'Investor\InvestorController@verify')->name('langganan-syer-pengesahan');
    // semak keanggotaaan
    Route::get('/keanggotaan/cari', 'Investor\SemakKeanggotaanController@findUser')->name('member.getuser');
    Route::get('/keanggotaan/semak', 'Investor\SemakKeanggotaanController@index')->name('member.verify');


    //Pembayaran manual
    Route::get('/langganan-syer/pembayaran-manual', 'Investor\InvestorController@buy_manual')->name('langganan-syer-manual');
    Route::post('/langganan-syer/pembayaran-manual', 'Investor\InvestorController@buy_manual_exe');

    Route::get('/langganan-syer/terima-kasih', 'SenangPayController@thankyou');


    Route::get('/hantar-bukti-pembayaran', 'Investor\InvestorController@paymentproof')->name('hantar-bukti-pembayaran');
    Route::post('/hantar-bukti-pembayaran', 'Investor\InvestorController@paymentproofexe')->middleware('optimizeImages');
    //

    Route::get('/login', 'Investor\InvestorController@index')->name('login');
    Route::get('/logmasuk', 'Investor\InvestorController@index')->name('login');
    Route::get('/LogMasuk', 'Investor\InvestorController@index')->name('login');
    Route::get('/', 'Investor\InvestorController@index')->name('login-root');
    Route::get('/logout', 'Investor\InvestorController@logout')->name('logout');
    // LOGIN FOR ANGGOTA
    Route::post('/auth/login/anggota', 'Investor\InvestorController@login_by_email_exe')->name('login-exe');
    Route::get('/forgot-password', 'Investor\InvestorController@forgot_password')->name('login');

    Route::get('/ikoop-migration', 'Investor\InvestorController@ikoopfirsttime')->name('ikoopfirsttime');
    Route::post('/ikoop-migration', 'Investor\InvestorController@ikoopfirsttimeexe');

    Route::get('/ikoop-migration/verification', 'Investor\InvestorController@ikoopfirsttime_2');

    Route::get('/ikoop-migration/verification/otp', 'Investor\InvestorController@ikoopfirsttime_3')->name('ikoopfirsttime3');

    Route::get('/ikoop-migration/verification/otp/send', 'Investor\InvestorController@sendOtp')->name('ikoopfirsttime3');

    Route::post('/ikoop-migration/verification/otp/submit', 'Investor\InvestorController@submitOTP')->name('ikoopfirsttime4');

    Route::get('/ikoop-migration/verification/thank-you', 'Investor\InvestorController@ikoopfirsttimethankyou')->name('ikoopfirsttimethankyou');

    Route::get('/email-activation/{token}', 'Investor\InvestorController@email_activation');

    Route::get('/dashboard', 'Investor\InvestorLoggedController@home')->name('dashboard');
    Route::get('/home', 'Investor\InvestorLoggedController@home')->name('dashboard');

    Route::get('/profile', 'Investor\InvestorLoggedController@edit_org_2');
    Route::get('/profile2', 'Investor\InvestorLoggedController@edit_org_2');

    Route::get('/syer', 'Investor\InvestorLoggedController@invest');
    Route::get('/syer/{id}', 'Investor\InvestorLoggedController@invest_detail');

    Route::get('/statement', 'Investor\InvestorLoggedController@statement');

    //DOWNLOAD PDF FOR INVESTOR
    Route::get('download_public', 'Investor\PdfController@download_public');

    Route::get('/linkstorage', function () {
        Artisan::call('storage:link');
    });

	if (env('ENABLE_DIVIDEN_MODULE', true)) {

	Route::get('/dividen', 'Investor\DividenController@index');

	Route::get('/dividen/download', 'Investor\DividenController@dividen_statement_download');


	Route::get('/dividen/withdraw', 'Investor\DividenController@withdraw');
	Route::post('/dividen/withdraw', 'Investor\DividenController@withdraw_exe');
	}


    Route::get('/change-password', 'Investor\InvestorLoggedController@changepassword');
    Route::post('/change-password', 'Investor\InvestorLoggedController@changePasswordExe');

    Route::get('/investor/edit/resend-email', 'Investor\InvestorLoggedController@activation_email');


    if (env('ENABLE_AFFILIATES', false)) {
        Route::get('/affiliates', 'Investor\AffiliatesController@invest');
        Route::post('/affiliates/withdraw', 'Investor\AffiliatesController@withdrawal');
        Route::get('/affiliates/penyata-komisen', 'Investor\AffiliatesController@getStatement');
        Route::get('/affiliates/penyata-komisen/cetak/{id}', 'Investor\AffiliatesController@printStatement');
        //        Route::get('/affiliates/withdraw', 'Investor\AffiliatesController@affliate_withdraw')->name('index');
        //        Route::post('/affiliates/withdraw', 'Investor\AffiliatesController@affliate_withdraw_exe')->name('index');
        Route::post('/affiliates/apply', 'Investor\AffiliatesController@apply_affiliate');
    }

    Route::view('terma-syarat', 'terma-syarat');
    Route::view('success-proof-payment-upload', 'investor.after-upload-proof-payment');

    Route::get('/dapatkan-kata-laluan', 'Auth\ResetPasswordController@showResetForm');
    Route::post('/kata-laluan/sahkan-kad-pengenalan', 'Auth\ResetPasswordController@verifyIc');
    Route::get('/kata-laluan/sahkan-no-telefon', 'Auth\ResetPasswordController@verifyMobileNumber');
    Route::any('/kata-laluan/hantar-kata-laluan-sementara', 'Auth\ResetPasswordController@sendTemporaryPassword');

    Route::get('/set-kata-laluan-baru', 'Investor\InvestorLoggedController@resetPassword');
    Route::post('/set-kata-laluan-baru', 'Investor\InvestorLoggedController@resetPasswordExe');

    // Permohonan Berhenti
    Route::get('/permohonan-berhenti', 'Investor\InvestorLoggedController@terminate_membership');
    Route::post('/permohonan-berhenti', 'Investor\InvestorLoggedController@terminate_membership_submit');
    Route::get('/permohonan-aktif', 'Investor\InvestorLoggedController@reactivate_membership');
    Route::post('/permohonan-aktif', 'Investor\InvestorLoggedController@reactivate_membership_submit');
    // Buy Share
    Route::prefix('langgan-syer')->name('share.')->namespace('Investor')->group(function () {
        Route::get('', 'BuyShareController@buy')->name('buy');
        Route::post('', 'BuyShareController@store_buy')->name('buy');
        Route::get('pengesahan', 'BuyShareController@verify')->name('verify');
    });

    //SenangPay: Do not use auth middleware
    Route::post('/payment-gateway/senang-pay/submit', 'SenangPayController@submit')->name('senang-pay-submit');
    Route::post('/payment-gateway/senang-pay/submit-recurring', 'SenangPayController@submitRecurring')->name('senang-pay-submit-recurring');
    Route::get('/pembelian-share/terima-kasih-s', 'SenangPayController@result'); //temp route
    Route::get('/payment-gateway/senang-pay/result', 'SenangPayController@result');
    Route::any('/payment-gateway/call-backend/senang-pay', 'SenangPayController@callback')->name('senang-pay-callback');

    //Profile
    Route::middleware(['auth'])->prefix('investor')->name('investor.')->namespace('Investor')->group(function () {
        Route::post('edit/info', 'ProfileController@editInfoPemohon');
        Route::post('edit/attachment', 'ProfileController@editInfoMykad');
        Route::post('edit/address', 'ProfileController@editAlamatPemohon');
        Route::post('edit/contact', 'ProfileController@editKontak');
        Route::post('edit/jawatan', 'ProfileController@editPekerjaan');
        Route::post('edit/bank', 'ProfileController@editBank');
        Route::post('edit/waris', 'ProfileController@editWaris');
        Route::post('profile/submit', 'ProfileController@submit')->name('profile.submit');
    });

    Route::group(['middleware' => 'auth', 'prefix' => 'transaksi', 'namespace' => 'Investor\Transactions'], function () {

        Route::group(['prefix' => 'log'], function () {
            Route::get('/', 'LogsController@index')->name('investor.transactions.logs.index');
        });
    });
};

$admin = function () {

    //temp solution for when admin close browser, then open back and go to admin route while still logged in, the system
    //will redirect to /home. Need to fix this later
    Route::get('/home', function () {
        return redirect('admin/dashboard');
    });

    //SenangPay, no auth
    Route::any('/payment-gateway/call-backend/senang-pay', 'SenangPayController@callback')->name('senang-pay-callback');

    //Members
    Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
        Route::get('members/dashboard', 'MemberController@viewDashboard')->name('member.dashboard');
        Route::get('members', 'MemberController@index')->name('member.list');
        Route::get('members/new', 'Members\NewApplicantsController@index')->name('member.new');
        Route::get('members/ikoop', 'Members\IkoopApplicantsController@index')->name('member.ikoop');
        Route::get('members/reviewed', 'Members\ReviewedApplicantsController@index')->name('member.reviewed');

resources/views/admin/includes/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                2020 . Sistem Pengurusan Anggota KoPPIM (V3)
            </div>
        </div>
    </div>
</footer>

resources/views/admin/includes/topbar.blade.php
<div class="navbar navbar-expand flex-column flex-md-row navbar-custom">
    <div class="container-fluid">
        <!-- LOGO -->
        <a href="/" class="navbar-brand mr-0 mr-md-2 logo">
            <span class="logo-lg">
                <img src="{{asset('img/logo-koppim.png')}}" height="24" />

            </span>
            <span class="logo-sm">
                <img src="{{asset('img/logo-koppim.png')}}" height="24" />
            </span>
        </a>

        <ul class="navbar-nav bd-navbar-nav flex-row list-unstyled menu-left mb-0">
            <li class="">
                <button class="button-menu-mobile open-left disable-btn">
                    <i data-feather="menu" class="menu-icon"></i>
                    <i data-feather="x" class="close-icon"></i>
                </button>
            </li>
        </ul>

        <ul class="navbar-nav flex-row ml-auto d-flex align-items-center list-unstyled topnav-menu float-right mb-0">
            <li class="dropdown d-none d-lg-block">
                <a class="dropdown-toggle mr-0 btn btn btn-sm btn-rounded btn-primary align-items-center" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <svg class="w-5 h-5 text-yellow-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                    </svg>
                    <span class="font-weight-bold">Tindakan Admin</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    @can('tambah-anggota')
                    <!-- item-->
                    <a href="{{route('admin.member.create')}}" class="dropdown-item notify-item">
                        Daftarkan Anggota (Manual)
                    </a>
                    @endcan
                    @can('sahkan-maklumat-anggota')
                    <a href="{{route('admin.member.new')}}" class="dropdown-item notify-item">
                        <span> Semak Permohonan Anggota</span>
                    </a>
                    @endcan
                    @can('luluskan-permohonan-anggota')
                    <a href="{{route('admin.member.reviewed')}}" class="dropdown-item notify-item">
                        <span>Luluskan Permohonan Anggota </span>
                    </a>
                    @endcan
                    @can('sahkan-bayaran-manual')
                    <a href="/admin/tx/manual" class="dropdown-item notify-item">
                        <span> Semak Bayaran Manual</span>
                    </a>
                    @endcan
                    @can('luluskan-bayaran-manual')
                    <a href="/admin/tx/approval" class="dropdown-item notify-item">
                        <span> Luluskan Bayaran Manual</span>
                    </a>
                    @endcan
                </div>
            </li>
            <li class="dropdown notification-list ">
                <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <div class="media user-profile ">
                        <div class="media-body text-right">
                            <h6 class="pro-user-name ml-2 my-0">
                                <span>{{ Auth::user()->name }}</span>

                            </h6>
                        </div>
                        <span data-feather="chevron-down" class="ml-2 align-self-center"></span>
                    </div>
                </a>
                <div class="dropdown-menu profile-dropdown-items dropdown-menu-right">
                    <a href="/admin/my-profile" class="dropdown-item notify-item">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                        <span>Profil Saya</span>
                    </a>
                    <a href="/admin/logout" class="dropdown-item notify-item">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                        </svg>
                        <span>Log Keluar</span>
                    </a>
                </div>
            </li>
        </ul>
    </div>

</div>